INSERT INTO TBL_PRODUCT (PRICE, BADONGUERS) VALUES (123, 'Oi');
INSERT INTO TBL_PRODUCT (PRICE, BADONGUERS) VALUES (888, 'Hakai');
INSERT INTO TBL_PRODUCT (PRICE, BADONGUERS) VALUES (94356, 'BANKAI!');
INSERT INTO TBL_PRODUCT (PRICE, BADONGUERS) VALUES (123, 'Maçã!');